kind: Deployment
apiVersion: apps/v1

metadata:
  name: mysql
  labels:
    app: mysql
    project: expense
    environment: development
  namespace: ex-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      project: expense
      environment: development
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        environment: development
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: ex-ns
  labels:
    app: mysql
    project: expense
    environment: development
spec:
  type: ClusterIP
  selector:
    app: mysql
    project: expense
    environment: development
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
        
