kind: Deployment
apiVersion: apps/v1
namespace: ex-ns
metadata:
  name: mysql
  labels:
    app: mysql
    project: expense
    environment: development
specc:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      project: expense
      environment: development
  template:
    metadata:
      labels:
        app: mysql
        project: expense
        environment: development
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        
