kind: configMap
apiVersion: v1
metadata:
  name: backend-config
  labels:
    component: backend
    environment: development
    project: expense
data:
  DB_HOST: mysql

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-apps
  labels:
    component: backend
    environment: development
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      environment: development
      project: expense
  template:
    metadata:
      labels:
        component: backend
        environment: development
        project: expense
    spec:
      containers:
        - name: backend-app
          image: joindevops/backend:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "125m"
          envFrom:
            - configMapRef:
                name: backend-config
---
kind: Service
apiVersion: v1
type: ClusterIP
metadata:
  name: backend-service
  labels:
    component: backend
    environment: development
    project: expense
spec:
  selector:
    component: backend
    environment: development
    project: expense  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: backend-hpa
  labels:
    component: backend
    environment: development
    project: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-apps
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          targetAverageUtilization: 15

