kind: Service
apiVersion: v1
metadata:
  name: lb 
spec:
  type: LoadBalancer
  selector:
    app: backend
    project: expense
    environment: development
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80