# in K8s limits and requests are used to manage resource allocation for containers running in pods.
# limits define the maximum amount of resources that a container can use, while requests define the minimum amount of resources that a container needs to run.
# limits and requests can be defined for CPU and memory resources.
# defining limits and requests helps ensure that containers have the resources they need to run properly, while also preventing them from using too many resources and impacting other containers running in the same pod or node.
# limits and requests can be defined using the resources field in the container specification.
# if its not defined kubernetes will not enforce any resource constraints on the container.
kind: Pod
apiVersion: v1
metadata:
  name: resource-limits-requests
spec:
  containers:
    - name: my-container
      image: nginx:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "500m"
