apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    app: backend
    project: expense
    environment: development
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80