kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: rs
  labels:
    name: ReplicaSet
    component: backend
    project: expense
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
      project: expense
      environment: development

  template:
    metadata:
      labels:
        component: backend
        project: expense
        environment: development
    spec:
      containers:
      - name: backend
        image: nginx
        