kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: rs-pod
  labels:
    name: replica-set
    component: backend
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      name: replica-set
      component: backend
      environment: development
  template:
    metadata:
      name: rs-pod
      labels:
        name: replica-set
        component: backend
        environment: development
    spec:
      containers:
      - name: nginx
        image: nginx