kind: Pod
apiVersion: v1
metadata:
  name: pod-dy 
  labels:
    purpose: test-sc
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-dynamic-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic-volume
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1a
---
kind: Service
apiVersion: v1
metadata:
  name: pod-dy-service
  labels:
    purpose: test-sc
spec:
  type: LoadBalancer
  selector:
    purpose: test-sc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081