kind: Pod
apiVersion: v1
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMouts:
    - name: ebs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-pvc