kind: Pod
apiVersion: v1
metadata:
  name: pod-volume
  labels:
    purpose: test-ebs
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-pvc
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
---
kind: Service
apiVersion: v1
metadata:
  name: pod-volume-service
  labels:
    purpose: test-ebs
spec:
  type: ClusterIP
  selector:
    purpose: test-ebs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80