kind: Pod
apiVersion: v1
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-pvc
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a