apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0a994c0ea89410720
