kind: Pod
apiVersion: v1
metadata:
  name: efs-pod 
  labels:
    purpose: efs-test
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: efs-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: expense-efs
      persistentVolumeClaim:
        claimName: efs-pvc-expense
---
kind: Service
apiVersion: v1  
metadata:
  name: efs-service
spec:
  type: LoadBalancer
  selector: 
    purpose: efs-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30007
