kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
  # nodeSelector:
  #   hardware: gpu
  tolerations:
  - key: hardware
    operator: Equal
    value: gpu
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # Hard requirement
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - gpu

    # kubectl label nodes ip-192-168-50-18.ec2.internal hardware=gpu