kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
  # nodeSelector:
  #   hardware: gpu
  # tolerations:
  # - key: hardware
  #   operator: Equal
  #   value: gpu
  #   effect: NoSchedule
    # requiredDuringScheduling
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # Hard requirement
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - gpu
  #     preferredDuringScheduling # Soft requirement
  # affinity:
  #   nodeAffinity: 
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 1
  #       preference:
  #         matchExpressions:
  #         - key: hardware
  #           operator: In
  #           values:
  #           - memory-optimized

    # kubectl label nodes ip-192-168-50-18.ec2.internal hardware=gpu
 