kind: Pod
apiVersion: v1
metadata:
  name: pod-1
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    hardware: gpu
  tolerations:
  - key: hardware
    operator: Equal
    value: gpu
    effect: NoSchedule