kind: Pod
apiVersion: v1
metadata:
  name: tolation-example
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
  tolarations:
  - key: hardware
    operator: Equal
    value: gpu
    effect: NoSchedule
