kind: Pod
apiVersion: v1
metadata:
  name: expense-pod
  labels:
    purpose: efs-test
spec:
  containers:
    - name: nginx 
      image: nginx
      volumeMounts:
        - name: expense-efs
          mountPath: /usr/share/nginx/html
  volumes:
    - name: expense-efs
      persistentVolumeClaim:
        claimName: efs-pvc-expense
---
kind: Service
apiVersion: v1
metadata:
  name: expense-service
spec:
  type: LoadBalancer
  selector:
    purpose: efs-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80