kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-pvc-expense
spec:
  storageClassName: efs-sc-expense
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---
