apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::177107204587:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-Pps5GJKcFe4d
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::177107204587:user/suresh
      username: suresh
      groups:
        - expense-trainee
metadata:
  creationTimestamp: null
  name: aws-auth
  namespace: kube-system
  