kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: expense
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: expense
subjects:
- kind: User
  name: suresh # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
